export const options = [
    { value: 'fashion', label: 'Moda', active: false },
    { value: 'nature', label: 'Natureza', active: false },
    { value: 'backgrounds', label: 'Fundos', active: false },
    { value: 'science', label: 'Ciência', active: false },
    { value: 'education', label: 'Educação', active: false },
    { value: 'people', label: 'Pessoas', active: false },
    { value: 'feelings', label: 'Sentimentos', active: false },
    { value: 'religion', label: 'Religião', active: false },
    { value: 'health', label: 'Saúde', active: false },
    { value: 'places', label: 'Locais', active: false },
    { value: 'animals', label: 'Animais', active: false },
    { value: 'industry', label: 'Indústria', active: false },
    { value: 'food', label: 'Comida', active: false },
    { value: 'computer', label: 'Computador', active: false },
    { value: 'sports', label: 'Esportes', active: false },
    { value: 'transportation', label: 'Transporte', active: false },
    { value: 'travel', label: 'Viagem', active: false },
    { value: 'buildings', label: 'Edifícios', active: false },
    { value: 'business', label: 'Negócios', active: false },
    { value: 'music', label: 'Música', active: false },
];