export const options = [
    { value: 'fashion', label: 'Moda' },
    { value: 'nature', label: 'Natureza' },
    { value: 'backgrounds', label: 'Fundos' },
    { value: 'science', label: 'Ciência' },
    { value: 'education', label: 'Educação' },
    { value: 'people', label: 'Pessoas' },
    { value: 'feelings', label: 'Sentimentos' },
    { value: 'religion', label: 'Religião' },
    { value: 'health', label: 'Saúde' },
    { value: 'places', label: 'Locais' },
    { value: 'animals', label: 'Animais' },
    { value: 'industry', label: 'Indústria' },
    { value: 'food', label: 'Comida' },
    { value: 'computer', label: 'Computador' },
    { value: 'sports', label: 'Esportes' },
    { value: 'transportation', label: 'Transporte' },
    { value: 'travel', label: 'Viagem' },
    { value: 'buildings', label: 'Edifícios' },
    { value: 'business', label: 'Negócios' },
    { value: 'music', label: 'Música' },
];